const express = require('express')
const app = express()
const routes = require('./routes/routes.js')
const cookieParser = require('cookie-parser')
const path =require("path")

app.set('view engine','ejs')
app.use(express.urlencoded({extended: false}))
app.use(express.json())
app.use('/static', express.static('static'))
app.use(cookieParser())
app.use(routes)

app.listen(8080)
console.log("listening on 8080")